GET https://java-realestate-apirest-production.up.railway.app/properties
Content-Type: application/json


###GET 
https://java-realestate-apirest-production.up.railway.app/properties/country/Italia

Content-Type: application/json



###
POST https://java-realestate-apirest-production.up.railway.app/properties
Content-Type: application/json




###
DELETE https://java-realestate-apirest-production.up.railway.app/properties/1
Content-Type: application/json





###
PUT https://java-realestate-apirest-production.up.railway.app/properties
Content-Type: application/json


###
PUT https://java-realestate-apirest-production.up.railway.app/properties/1
Content-Type: application/json







