GET https://java-realestate-apirest-production.up.railway.app/properties
Content-Type: application/json


###GET 
https://java-realestate-apirest-production.up.railway.app/properties/country/España

Content-Type: application/json



###
POST https://java-realestate-apirest-production.up.railway.app/properties
Content-Type: application/json

{
    "pais": "España",
    "ciudad": "Madrid",
    "precio": 250000.00,
    "description": "Hermoso apartamento en el centro de Madrid.",
    "urlImagen": "http://example.com/image.jpg"
}

###
DELETE https://java-realestate-apirest-production.up.railway.app/properties/2
Content-Type: application/json





